### ISSUE TITLE
Chybí info_preprocess_header.h soubor.

### ISSUE THREAD

**Issue by budikpet** [AckeeEDU/mi-ios-2019#1]
Po naklonování projektu na větvi 01_advanced_xcode mi nešel projekt buildovat, protože v něm chybí info_preprocess_header.h.

**Comment by vosatom** [comment]
Ten by se ti měl vygenerovat, ale mě se taky negeneroval.
Generoval se ručně. 
Kdyžtak si ho stáhni z https://github.com/AckeeEDU/mi-ios-2019/commit/cd16a14353a42155a00d09f546c7bd45666eae4e

**Comment by olejnjak** [comment]
Vyřešeno ve větvi `06-ci`
